// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-ua4XLyrFdOFeacCT_SDwlWM3hN6q8_M', // Verify if this key works for Web
    appId: '1:446388818157:web:6eef355b58feb9e477fce4', // Placeholder: Update with your real Web App ID from Firebase Console
    messagingSenderId: '446388818157',
    projectId: 'mobileapp-23b11',
    authDomain: 'mobileapp-23b11.firebaseapp.com',
    storageBucket: 'mobileapp-23b11.firebasestorage.app',
    measurementId: null,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-ua4XLyrFdOFeacCT_SDwlWM3hN6q8_M',
    appId: '1:446388818157:android:ef5c9e5b58feb9e477fce4',
    messagingSenderId: '446388818157',
    projectId: 'mobileapp-23b11',
    storageBucket: 'mobileapp-23b11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'demo-ios-api-key',
    appId: '1:123456789:ios:demo-app-id',
    messagingSenderId: '123456789',
    projectId: 'demo-project-id',
    storageBucket: 'demo-project-id.appspot.com',
    iosClientId: 'demo-ios-client-id.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelagency',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'demo-macos-api-key',
    appId: '1:123456789:ios:demo-app-id',
    messagingSenderId: '123456789',
    projectId: 'demo-project-id',
    storageBucket: 'demo-project-id.appspot.com',
    iosClientId: 'demo-ios-client-id.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelagency',
  );
}
